// scripts/seedRiddles.js
require('dotenv').config();
const { supabase } = require('../src/config/supabaseClient');

const RIDDLES_DATA = [
  // ==========================================
  // ROUND 1 (10 Challenges — Easy / Basics)
  // ==========================================
  {
    roundNumber: 1,
    code: 'R1-001',
    type: 'riddle',
    question: 'I have no feet, but everyone passes through me.\nI stand at the beginning and end of your journey.',
    correctAnswer: 'Door',
    acceptedAnswers: ['door', 'the door', 'doors', 'main door', 'entrance door', 'front door'],
    hint: 'You walk through it every time you enter or leave the hall.',
    points: 100,
    penalty: 10,
  },
  {
    roundNumber: 1,
    code: 'R1-002',
    type: 'riddle',
    question: 'I have many legs, but I never walk.\nI carry you while you rest.',
    correctAnswer: 'Chair',
    acceptedAnswers: ['chair', 'the chair', 'a chair', 'chairs', 'seat', 'seats', 'bench'],
    hint: 'Take a seat and look right beneath you.',
    points: 100,
    penalty: 10,
  },
  {
    roundNumber: 1,
    code: 'R1-003',
    type: 'riddle',
    question: 'I am always under your feet,\nBut you rarely think about me.',
    correctAnswer: 'Floor',
    acceptedAnswers: ['floor', 'the floor', 'ground', 'the ground', 'flooring', 'tiles', 'carpet'],
    hint: 'Look directly down below your shoes.',
    points: 100,
    penalty: 10,
  },
  {
    roundNumber: 1,
    code: 'R1-004',
    type: 'puzzle',
    question: 'I have a handle, but I am not a door.\nYou use me to write your ideas.',
    correctAnswer: 'Pen',
    acceptedAnswers: ['pen', 'a pen', 'the pen', 'ballpoint pen', 'ink pen', 'pencil'],
    hint: 'Mightier than the sword and held in your fingers.',
    points: 100,
    penalty: 10,
  },
  {
    roundNumber: 1,
    code: 'R1-005',
    type: 'riddle',
    question: 'I have four legs and a flat top.\nMany things rest on me.',
    correctAnswer: 'Table',
    acceptedAnswers: ['table', 'the table', 'a table', 'desk', 'the desk', 'bench'],
    hint: 'Laptops, papers, and cups rest on its flat surface.',
    points: 100,
    penalty: 10,
  },
  {
    roundNumber: 1,
    code: 'R1-006',
    type: 'puzzle',
    question: 'I make things bright when darkness arrives.\nFind me where electricity becomes light.',
    correctAnswer: 'Switch',
    acceptedAnswers: ['switch', 'light switch', 'the switch', 'electric switch', 'button', 'switch board'],
    hint: 'You flip or toggle it on the wall to brighten the room.',
    points: 100,
    penalty: 10,
  },
  {
    roundNumber: 1,
    code: 'R1-007',
    type: 'riddle',
    question: 'I have hands, but I cannot hold.\nI have a face, but I cannot smile.\nI never stop ticking.',
    correctAnswer: 'Clock',
    acceptedAnswers: ['clock', 'the clock', 'wall clock', 'watch', 'the wall clock', 'time'],
    hint: 'Hangs high on the wall showing minutes and hours.',
    points: 100,
    penalty: 10,
  },
  {
    roundNumber: 1,
    code: 'R1-008',
    type: 'puzzle',
    question: 'Feed me all your waste, wrappers, and paper.\nI keep the room clean, but I am never full for long.',
    correctAnswer: 'Dustbin',
    acceptedAnswers: ['dustbin', 'the dustbin', 'trash can', 'garbage can', 'waste bin', 'bin', 'dust bin', 'trashcan'],
    hint: 'Standing in the corner waiting for used wrappers and scrap.',
    points: 100,
    penalty: 10,
  },
  {
    roundNumber: 1,
    code: 'R1-009',
    type: 'riddle',
    question: 'I cover what lets sunlight in,\nI flutter when the breeze rolls by.\nPull me aside to see outside.',
    correctAnswer: 'Curtain',
    acceptedAnswers: ['curtain', 'curtains', 'the curtain', 'the curtains', 'window curtain', 'drapes'],
    hint: 'Fabric hanging beside the window panes.',
    points: 100,
    penalty: 10,
  },
  {
    roundNumber: 1,
    code: 'R1-010',
    type: 'puzzle',
    question: 'I speak on the board without making a sound.\nThe more I write, the shorter I get.',
    correctAnswer: 'Marker',
    acceptedAnswers: ['marker', 'whiteboard marker', 'the marker', 'chalk', 'board marker', 'pen'],
    hint: 'Held by the professor writing notes on the whiteboard.',
    points: 100,
    penalty: 10,
  },

  // ==========================================
  // ROUND 2 (10 Challenges — Hall, Media & Display)
  // ==========================================
  {
    roundNumber: 2,
    code: 'R2-001',
    type: 'riddle',
    question: 'I have no eyes, but I help everyone see.\nI turn small images into something big.',
    correctAnswer: 'Projector',
    acceptedAnswers: ['projector', 'the projector', 'a projector', 'overhead projector', 'video projector'],
    hint: 'Mounted near the ceiling, throwing light across the room.',
    points: 150,
    penalty: 10,
  },
  {
    roundNumber: 2,
    code: 'R2-002',
    type: 'riddle',
    question: 'I am not a wall, but I show what the projector wants you to see.\nEveryone looks at me.',
    correctAnswer: 'Screen',
    acceptedAnswers: ['screen', 'the screen', 'projector screen', 'display screen', 'white screen', 'projection screen'],
    hint: 'The giant white surface hanging at the front where videos play.',
    points: 150,
    penalty: 10,
  },
  {
    roundNumber: 2,
    code: 'R2-003',
    type: 'puzzle',
    question: 'I am small, but I can control a big screen.\nPress my buttons to change what you see.',
    correctAnswer: 'Remote',
    acceptedAnswers: ['remote', 'remote control', 'the remote', 'controller', 'remote controller'],
    hint: 'A handheld device with buttons for the projector or AC.',
    points: 150,
    penalty: 10,
  },
  {
    roundNumber: 2,
    code: 'R2-004',
    type: 'riddle',
    question: 'I have no voice, but I carry important announcements.\nFind the place where information is displayed.',
    correctAnswer: 'Notice Board',
    acceptedAnswers: ['notice board', 'noticeboard', 'the notice board', 'bulletin board', 'display board'],
    hint: 'Pinned with announcements, schedules, and circulars on the corridor wall.',
    points: 150,
    penalty: 10,
  },
  {
    roundNumber: 2,
    code: 'R2-005',
    type: 'riddle',
    question: 'I can see outside, but I cannot leave the room.\nOpen me and fresh air may enter.',
    correctAnswer: 'Window',
    acceptedAnswers: ['window', 'the window', 'windows', 'glass window', 'window pane'],
    hint: 'Look towards the outer walls with glass panes.',
    points: 150,
    penalty: 10,
  },
  {
    roundNumber: 2,
    code: 'R2-006',
    type: 'puzzle',
    question: 'I show you where you are going,\nBut I never move.',
    correctAnswer: 'Sign Board',
    acceptedAnswers: ['sign board', 'signboard', 'sign', 'the sign board', 'direction board', 'arrow board', 'name board'],
    hint: 'Fixed on walls or doors to guide visitors with arrows and titles.',
    points: 150,
    penalty: 10,
  },
  {
    roundNumber: 2,
    code: 'R2-007',
    type: 'puzzle',
    question: 'I have a tail or live on wireless air.\nI have two ears you click, but I am not a real rodent.',
    correctAnswer: 'Mouse',
    acceptedAnswers: ['mouse', 'computer mouse', 'the mouse', 'wireless mouse', 'optical mouse'],
    hint: 'Sits beside the laptop controlling the pointer on screen.',
    points: 150,
    penalty: 10,
  },
  {
    roundNumber: 2,
    code: 'R2-008',
    type: 'riddle',
    question: 'I have holes in the wall waiting silently.\nPlug your charger into me to bring your dead battery to life.',
    correctAnswer: 'Socket',
    acceptedAnswers: ['socket', 'plug', 'power socket', 'wall socket', 'plug point', 'switchboard', 'outlet', 'power point'],
    hint: 'Where participants insert phone charging adapters.',
    points: 150,
    penalty: 10,
  },
  {
    roundNumber: 2,
    code: 'R2-009',
    type: 'puzzle',
    question: 'I fit inside your pocket, small as a thumb.\nPlug me into a port, and gigabytes of files appear.',
    correctAnswer: 'Pen Drive',
    acceptedAnswers: ['pen drive', 'pendrive', 'usb', 'flash drive', 'usb drive', 'thumb drive'],
    hint: 'Pocket storage device plugged into USB ports.',
    points: 150,
    penalty: 10,
  },
  {
    roundNumber: 2,
    code: 'R2-010',
    type: 'riddle',
    question: 'I never sleep, I never blink.\nA silent eye mounted up high, watching over everyone.',
    correctAnswer: 'CCTV',
    acceptedAnswers: ['cctv', 'cctv camera', 'camera', 'security camera', 'the camera', 'surveillance camera'],
    hint: 'Mounted in the corner of the ceiling for campus security.',
    points: 150,
    penalty: 10,
  },

  // ==========================================
  // ROUND 3 (10 Challenges — Sound, Comfort & Tech)
  // ==========================================
  {
    roundNumber: 3,
    code: 'R3-001',
    type: 'riddle',
    question: "You cannot see me, but you can hear me.\nI make one person's voice reach everyone.",
    correctAnswer: 'Mic',
    acceptedAnswers: ['mic', 'microphone', 'the mic', 'the microphone', 'wireless mic', 'collar mic', 'mike'],
    hint: 'Placed on the podium or held in hand by the speaker.',
    points: 200,
    penalty: 15,
  },
  {
    roundNumber: 3,
    code: 'R3-002',
    type: 'riddle',
    question: 'I help turn a voice into sound that can reach the whole hall.\nFind where the sound comes from.',
    correctAnswer: 'Speaker',
    acceptedAnswers: ['speaker', 'speakers', 'the speaker', 'loudspeaker', 'loud speaker', 'sound box', 'sound system', 'audio speaker'],
    hint: 'Box mounted high on the walls pumping out sound.',
    points: 200,
    penalty: 15,
  },
  {
    roundNumber: 3,
    code: 'R3-003',
    type: 'riddle',
    question: 'I make the room comfortable without blowing wind with my hands.\nFind the machine that keeps you cool.',
    correctAnswer: 'AC',
    acceptedAnswers: ['ac', 'air conditioner', 'the ac', 'a/c', 'air conditioning', 'air cooler'],
    hint: 'Hangs high up on the wall blowing chilled air.',
    points: 200,
    penalty: 15,
  },
  {
    roundNumber: 3,
    code: 'R3-004',
    type: 'puzzle',
    question: 'I have many keys,\nBut I cannot open a door.\nI can create words with every touch.',
    correctAnswer: 'Keyboard',
    acceptedAnswers: ['keyboard', 'the keyboard', 'computer keyboard', 'key board', 'typing keyboard'],
    hint: 'Has spacebar, enter, and letters from A to Z.',
    points: 200,
    penalty: 15,
  },
  {
    roundNumber: 3,
    code: 'R3-005',
    type: 'puzzle',
    question: 'I have pages but I am not a book.\nI help you remember important dates.',
    correctAnswer: 'Calendar',
    acceptedAnswers: ['calendar', 'the calendar', 'a calendar', 'wall calendar', 'desk calendar'],
    hint: 'Shows the 12 months, weeks, and holidays of the year.',
    points: 200,
    penalty: 15,
  },
  {
    roundNumber: 3,
    code: 'R3-006',
    type: 'riddle',
    question: 'I keep your secrets inside,\nBut I am not a treasure chest.',
    correctAnswer: 'Cupboard',
    acceptedAnswers: ['cupboard', 'the cupboard', 'almirah', 'cabinet', 'closet', 'locker', 'wardrobe', 'storage cabinet'],
    hint: 'Furniture with wooden or steel doors storing folders and items.',
    points: 200,
    penalty: 15,
  },
  {
    roundNumber: 3,
    code: 'R3-007',
    type: 'riddle',
    question: 'I spin in circles without getting dizzy.\nI have three blades, but I never cut anything.',
    correctAnswer: 'Fan',
    acceptedAnswers: ['fan', 'ceiling fan', 'the fan', 'the ceiling fan'],
    hint: 'Whirring high overhead on the ceiling circulating the breeze.',
    points: 200,
    penalty: 15,
  },
  {
    roundNumber: 3,
    code: 'R3-008',
    type: 'puzzle',
    question: 'I wrap around your head or rest in your ears.\nI bring music to your world without letting anyone else hear.',
    correctAnswer: 'Headphones',
    acceptedAnswers: ['headphones', 'earphones', 'headphone', 'earphone', 'airpods', 'headset', 'earbuds'],
    hint: 'Plugged into phones or laptops for private listening.',
    points: 200,
    penalty: 15,
  },
  {
    roundNumber: 3,
    code: 'R3-009',
    type: 'riddle',
    question: 'I have zips, pockets, and two straps.\nI ride on your back carrying your books and laptop everywhere.',
    correctAnswer: 'Bag',
    acceptedAnswers: ['bag', 'backpack', 'college bag', 'school bag', 'the bag', 'the backpack'],
    hint: 'Carried on the shoulders by every college student.',
    points: 200,
    penalty: 15,
  },
  {
    roundNumber: 3,
    code: 'R3-010',
    type: 'puzzle',
    question: 'I have blinking lights and small antennas.\nI connect you to the whole world without a single physical wire.',
    correctAnswer: 'Router',
    acceptedAnswers: ['router', 'wifi router', 'wi-fi router', 'the router', 'wifi', 'wi-fi', 'modem'],
    hint: 'The box radiating campus wireless internet signals.',
    points: 200,
    penalty: 15,
  },

  // ==========================================
  // ROUND 4 (10 Challenges — Stage & Surroundings)
  // ==========================================
  {
    roundNumber: 4,
    code: 'R4-001',
    type: 'riddle',
    question: 'I am not the stage, but I help you reach it.\nStep by step, I take you higher.',
    correctAnswer: 'Stage Steps',
    acceptedAnswers: ['stage steps', 'steps', 'stairs', 'stage stairs', 'the steps', 'the stairs', 'staircase'],
    hint: 'Climb these stairs to walk up to the podium.',
    points: 250,
    penalty: 15,
  },
  {
    roundNumber: 4,
    code: 'R4-002',
    type: 'riddle',
    question: 'I am where the speaker stands and everyone watches.\nPerformers love me.',
    correctAnswer: 'Stage',
    acceptedAnswers: ['stage', 'the stage', 'podium', 'dais', 'platform', 'main stage'],
    hint: 'The elevated wooden platform at the center front.',
    points: 250,
    penalty: 15,
  },
  {
    roundNumber: 4,
    code: 'R4-003',
    type: 'puzzle',
    question: 'You have climbed up, but now think about where people sit and watch the show.',
    correctAnswer: 'Chairs',
    acceptedAnswers: ['chairs', 'chair', 'seats', 'audience chairs', 'audience seats', 'the chairs', 'the seats', 'sofa'],
    hint: 'Look out from the stage towards the auditorium audience area.',
    points: 250,
    penalty: 15,
  },
  {
    roundNumber: 4,
    code: 'R4-004',
    type: 'riddle',
    question: 'I reflect your face,\nBut I never smile.',
    correctAnswer: 'Mirror',
    acceptedAnswers: ['mirror', 'a mirror', 'the mirror', 'looking glass', 'glass mirror'],
    hint: 'Shows your exact reflection.',
    points: 250,
    penalty: 15,
  },
  {
    roundNumber: 4,
    code: 'R4-005',
    type: 'riddle',
    question: "I am above you and chase away darkness.\nI don't need the Sun to shine.",
    correctAnswer: 'Light',
    acceptedAnswers: ['light', 'lights', 'the light', 'bulb', 'tube light', 'led', 'lamp', 'ceiling light', 'spotlight'],
    hint: 'Fixed to the ceiling, glowing brightly when switched on.',
    points: 250,
    penalty: 15,
  },
  {
    roundNumber: 4,
    code: 'R4-006',
    type: 'puzzle',
    question: 'I hold water but I am not a river.\nYou may find me when you need a drink.',
    correctAnswer: 'Water Dispenser',
    acceptedAnswers: ['water dispenser', 'water bottle', 'water cooler', 'dispenser', 'water filter', 'cooler', 'bottle', 'drinking water'],
    hint: 'Where thirsty participants go to refill cups or bottles.',
    points: 250,
    penalty: 15,
  },
  {
    roundNumber: 4,
    code: 'R4-007',
    type: 'riddle',
    question: 'I stand proudly on the stage with a sloping top.\nSpeakers rest their notes and microphones on me.',
    correctAnswer: 'Podium',
    acceptedAnswers: ['podium', 'lectern', 'the podium', 'the lectern', 'speaker stand', 'dais'],
    hint: 'The wooden standing desk at the center of the stage.',
    points: 250,
    penalty: 15,
  },
  {
    roundNumber: 4,
    code: 'R4-008',
    type: 'puzzle',
    question: 'I hang around your neck on a ribbon.\nI show your photo, name, and college to prove who you are.',
    correctAnswer: 'ID Card',
    acceptedAnswers: ['id card', 'id', 'identity card', 'badge', 'the id card', 'tag', 'id badge', 'lanyard'],
    hint: 'Every participant wears one on a lanyard around their neck.',
    points: 250,
    penalty: 15,
  },
  {
    roundNumber: 4,
    code: 'R4-009',
    type: 'riddle',
    question: 'I am bright red, filled with pressure, and wait silently on the wall.\nIn times of smoke and heat, I am your hero.',
    correctAnswer: 'Fire Extinguisher',
    acceptedAnswers: ['fire extinguisher', 'extinguisher', 'the fire extinguisher', 'red cylinder', 'fire cylinder'],
    hint: 'Red safety canister mounted on the corridor walls.',
    points: 250,
    penalty: 15,
  },
  {
    roundNumber: 4,
    code: 'R4-010',
    type: 'puzzle',
    question: 'I am smooth, shiny, and blank until you write.\nBut a single swipe of a duster erases all my thoughts.',
    correctAnswer: 'Whiteboard',
    acceptedAnswers: ['whiteboard', 'white board', 'the whiteboard', 'board', 'marker board'],
    hint: 'Large white board at the front written on with dry-erase markers.',
    points: 250,
    penalty: 15,
  },

  // ==========================================
  // ROUND 5 (10 Challenges — Finale & Treasure)
  // ==========================================
  {
    roundNumber: 5,
    code: 'R5-001',
    type: 'riddle',
    question: 'I am filled with knowledge,\nYet I never speak.\nStudents often search through me.',
    correctAnswer: 'Library',
    acceptedAnswers: ['library', 'bookshelf', 'book shelf', 'bookcase', 'the library', 'reading room', 'book rack'],
    hint: 'A quiet room lined with bookshelves and academic lore.',
    points: 500,
    penalty: 20,
  },
  {
    roundNumber: 5,
    code: 'R5-002',
    type: 'puzzle',
    question: 'I am near the entrance,\nBut I am not the door.\nI welcome visitors without speaking.',
    correctAnswer: 'Reception Desk',
    acceptedAnswers: ['reception desk', 'reception', 'front desk', 'help desk', 'registration desk', 'helpdesk', 'inquiry desk'],
    hint: 'The very first desk where teams register and get badges.',
    points: 500,
    penalty: 20,
  },
  {
    roundNumber: 5,
    code: 'R5-003',
    type: 'riddle',
    question: 'I can be opened and closed,\nAnd I connect this hall with the outside world.',
    correctAnswer: 'Door',
    acceptedAnswers: ['door', 'exit door', 'main door', 'the door', 'hall door', 'emergency exit'],
    hint: 'Swing it open to step out into the campus breeze.',
    points: 500,
    penalty: 20,
  },
  {
    roundNumber: 5,
    code: 'R5-004',
    type: 'riddle',
    question: 'The final destination is almost here.\nLook where everyone comes to perform, speak and celebrate.',
    correctAnswer: 'Stage',
    acceptedAnswers: ['stage', 'the stage', 'podium', 'dais', 'platform', 'auditorium stage'],
    hint: 'Where the winners will be called and the championship trophy given.',
    points: 500,
    penalty: 20,
  },
  {
    roundNumber: 5,
    code: 'R5-005',
    type: 'puzzle',
    question: 'Congratulations! You solved every clue!\nYour treasure is waiting at the place where the hunt began.',
    correctAnswer: 'Starting Point',
    acceptedAnswers: ['starting point', 'start point', 'treasure', 'start', 'origin', 'the treasure', 'starting line', 'registration desk'],
    hint: 'Head back to where your journey first took flight.',
    points: 500,
    penalty: 20,
  },
  {
    roundNumber: 5,
    code: 'R5-006',
    type: 'puzzle',
    question: 'You searched high,\nYou searched low,\nYou followed every clue.\nNow return to the place\nwhere your adventure first began.\nYour treasure is waiting there!',
    correctAnswer: 'Treasure',
    acceptedAnswers: ['treasure', 'the treasure', 'starting point', 'start point', 'start', 'starting line', 'origin'],
    hint: 'The grand finale box at the starting hub.',
    points: 500,
    penalty: 20,
  },
  {
    roundNumber: 5,
    code: 'R5-007',
    type: 'riddle',
    question: 'I have handles like a pot, and shine like gold or silver.\nOnly the champions get to lift me high.',
    correctAnswer: 'Trophy',
    acceptedAnswers: ['trophy', 'the trophy', 'cup', 'the cup', 'medal', 'shield', 'award', 'championship trophy'],
    hint: 'The gleaming golden cup waiting for the winning team.',
    points: 500,
    penalty: 20,
  },
  {
    roundNumber: 5,
    code: 'R5-008',
    type: 'puzzle',
    question: 'I am made of paper, stamped with prestige and signed by leaders.\nI prove that you competed and conquered.',
    correctAnswer: 'Certificate',
    acceptedAnswers: ['certificate', 'the certificate', 'award', 'diploma', 'participation certificate'],
    hint: 'Printed document awarded to winners and participants.',
    points: 500,
    penalty: 20,
  },
  {
    roundNumber: 5,
    code: 'R5-009',
    type: 'riddle',
    question: 'Open my clamshell body, awake my glowing brain.\nI calculate in nanoseconds, running code for your symposium.',
    correctAnswer: 'Laptop',
    acceptedAnswers: ['laptop', 'computer', 'the laptop', 'pc', 'notebook', 'the computer'],
    hint: 'Portable computing machine sitting on the coordinator desk.',
    points: 500,
    penalty: 20,
  },
  {
    roundNumber: 5,
    code: 'R5-010',
    type: 'puzzle',
    question: 'You started as seekers,\nYou decoded the night,\nYou ran through each checkpoint,\nWith teamwork and might.\nName the golden prize\nthat crowns every champion!',
    correctAnswer: 'Victory',
    acceptedAnswers: ['victory', 'treasure', 'winner', 'champion', 'success', 'trophy', 'first place', 'the victory', 'the treasure'],
    hint: 'What awaits the fastest team at the end of the treasure hunt.',
    points: 500,
    penalty: 20,
  },
];

async function seed() {
  console.log('[seeder] Loading rounds from database...');
  const { data: rounds, error: rErr } = await supabase.from('rounds').select('*').order('round_number', { ascending: true });
  if (rErr || !rounds || rounds.length === 0) {
    console.error('Failed to load rounds:', rErr);
    process.exit(1);
  }

  const roundMap = {};
  rounds.forEach((r) => {
    roundMap[r.round_number] = r.id;
  });

  console.log('[seeder] Cleaning up old challenges...');
  await supabase.from('answer_attempts').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  await supabase.from('team_challenges').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  const { error: delErr } = await supabase.from('challenges').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  if (delErr) {
    console.warn('Warning during old challenges delete:', delErr.message);
  }

  console.log('[seeder] Inserting 50 Riddles & Simple Puzzles (10 per round across 5 rounds)...');
  const payload = RIDDLES_DATA.map((item) => ({
    round_id: roundMap[item.roundNumber],
    code: item.code,
    type: item.type,
    question: item.question,
    options: null, // 100% riddle / puzzle, zero quiz
    correct_answer: item.correctAnswer,
    accepted_answers: item.acceptedAnswers,
    hint: item.hint,
    points: item.points,
    penalty: item.penalty,
    is_active: true,
  }));

  const { data: inserted, error: insErr } = await supabase.from('challenges').insert(payload).select('id, code, round_id, type');
  if (insErr) {
    console.error('Insert failed:', insErr);
    process.exit(1);
  }

  console.log(`[seeder] Successfully seeded ${inserted.length} challenges (10 per round)!`);
  
  // Count per round:
  const counts = {};
  inserted.forEach((c) => {
    const rNum = Object.keys(roundMap).find((k) => roundMap[k] === c.round_id);
    counts[`Round ${rNum}`] = (counts[`Round ${rNum}`] || 0) + 1;
  });
  console.log('Challenges per round:', counts);
  process.exit(0);
}

seed();
